[build]
command = """
  curl -L https://foundry.paradigm.xyz | bash && \
  source $HOME/.bashrc && \
  $HOME/.foundry/bin/foundryup && \
  export PATH="$PATH:$HOME/.foundry/bin" && \
  echo "export PATH=$PATH" >> $HOME/.bashrc && \
  yarn run docs
"""
publish = "build/site"