[build]
command = "rustup toolchain install stable && cargo install --git https://github.com/foundry-rs/foundry --profile release --locked forge cast chisel anvil && yarn run docs"
publish = "build/site"