name: docs
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build-docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up environment
        uses: ./.github/actions/setup
      - run: bash scripts/git-user-config.sh
      - run: npm run prepare-docs
      - run: git add -f docs
      - run: git commit -m "Update docs"
      - run: git push --all origin
