name: docs
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build-docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: actions/cache@v4
        id: cache
        with:
          path: '**/node_modules'
          key: npm-v3-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
        shell: bash
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Set up environment
        uses: ./.github/actions/setup
      - run: bash scripts/git-user-config.sh
      - run: npm run prepare-docs
      - run: git add -f docs
      - run: git commit -m "Update docs"
      - run: git push --all origin
